services: 
  grafana:
    image: grafana/grafana:latest
    ports: 
      - '3000:3000'
    networks: 
      - loki-net

  loki:
    image: grafana/loki:latest
    ports: 
      - '3100:3100'
    networks: 
      - loki-net
    depends_on:
      - grafana

  postgres: 
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    depends_on:
      - grafana
      - loki
    networks:
      - loki-net
      
  database: 
    image: db
    build:
      context: ./DataBase
    ports:
      - "8000:8000"
    networks: 
      - loki-net
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/user/health']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      - grafana
      - loki
      - postgres

  bot:
    image: bot
    build:
      context: ./Bot
    networks: 
      - loki-net
    develop:
      watch:
      - path: ./Bot
        action: rebuild
        # - path: ./Bot/handlers
        #   action: sync
        #   target: /app/handler
        # - path: ./Bot/keyboards
        #   action: sync
        #   target: /app/keyboard

    depends_on:
      database:
        condition: service_healthy

volumes:
  postgres_data:
    
networks:
  loki-net:
    driver: bridge
